<div class="boundary" id="b1"></div>
<div class="boundary" id="b2"></div>
<div class="boundary" id="b3"></div>
<div class="boundary" id="b4"></div>
<div class="boundary" id="b5"></div>
<div class="boundary" id="b6"></div>
<div class="boundary" id="b7"></div>
<div class="boundary" id="b8"></div>
<div class="boundary" id="b9"></div>
<div class="boundary" id="b10"></div>
<div class="boundary" id="b11"></div>
<div class="boundary" id="b12"></div>
<div class="boundary" id="b13"></div>
<div class="boundary" id="b14"></div>
<div class="boundary" id="b15"></div>
<div class="boundary" id="b16"></div>
<div class="boundary" id="b17"></div>
<div class="boundary" id="b18"></div>
<div class="boundary" id="b19"></div>
<div class="boundary" id="b20"></div>
<div id="hanger1" class="levelImages"></div>
<div id="hanger2" class="levelImages"></div>
<div id="present_1_single" class="levelImages"></div>
<div id="present_1_gap" class="levelImages"></div>
<div id="present_2_bottom" class="levelImages"></div>
<div id="present_2_middle" class="levelImages"></div>
<div id="present_2_top" class="levelImages"></div>
<div id="tree" class="levelImages"></div>